Cabal-version:       2.2
Name:                happstack-authenticate
Version:             3.1.3
Synopsis:            Happstack Authentication Library
Description:         A themeable authentication library with support for username+password
Homepage:            http://www.happstack.com/
License:             BSD-3-Clause
License-file:        LICENSE
Author:              Jeremy Shaw.
Maintainer:          jeremy@seereason.com
Copyright:           2011-2015 SeeReason Partners, LLC
Category:            Web
Build-type:          Simple
tested-with:         GHC==8.0.2, GHC==8.2.2, GHC==8.4.4, GHC==8.6.5, GHC==8.8.4, GHC==8.10.7, GHC==9.0.2, GHC==9.2.2
data-files:
  messages/core/en.msg
  messages/username-problem/en.msg
  messages/openid/error/en.msg
  messages/openid/partials/en.msg
  messages/password/error/en.msg
  messages/password/partials/en.msg

flag Debug
    Description: enable debug output
    Default: False
    Manual: True

flag arch_javascript
  description: Stand-in for arch(javascript). Remove if not using haskell.nix.
  default: False
  manual: True

source-repository head
    type:     git
    location: https://github.com/Happstack/happstack-authenticate.git

common shared-properties
   default-language: Haskell2010

common shared-ghcjs-properties
  default-language: Haskell2010
  if impl(ghcjs) || (arch(javascript) || arch(wasm32))
    build-depends:     base
                     , base64-bytestring            >= 1.0  && < 1.3
                     , chili                        >= 0.4.2
                     , aeson
                     , bytestring
                     , containers
                     , cereal
                     , http-types
                     , lens
                     , mtl
                     , safecopy
                     , shakespeare                  >= 2.0  && < 2.3
                     , stm
                     , text
                     , template-haskell
                     , unordered-containers
                     , userid
                     , web-routes

  if impl(ghcjs)
    build-depends:  ghcjs-base, ghcjs-dom
  if (arch(javascript) || arch(wasm32))
    build-depends:  ghcjs-base >= 0.8.0.2, ghcjs-dom-javascript >= 0.9.9.3

Library
  import:              shared-properties
  import:              shared-ghcjs-properties
  ghc-options:         -Werror=incomplete-patterns
  hs-source-dirs:      src
  if flag(Debug)
    cpp-options: "-DDEBUG"

  Exposed-modules:
                        Happstack.Authenticate.Core
                        Happstack.Authenticate.Password.Core
                        Happstack.Authenticate.Password.URL

  if impl(ghcjs) || (arch(javascript) || arch(wasm32))
   Exposed-modules:
                        Happstack.Authenticate.Client

  -- flag(arch_javascript): stand-in for arch(javascript); remove if not using haskell.nix.
  if !(impl(ghcjs) || flag(arch_javascript))
   Exposed-modules:
                        Happstack.Authenticate.Handlers
                        Happstack.Authenticate.Route
                        Happstack.Authenticate.Password.Handlers
                        Happstack.Authenticate.Password.Route


--                        Happstack.Authenticate.OpenId.Controllers
--                        Happstack.Authenticate.OpenId.Core
--                        Happstack.Authenticate.OpenId.Partials
--                        Happstack.Authenticate.OpenId.PartialsURL
--                        Happstack.Authenticate.OpenId.Route
--                        Happstack.Authenticate.OpenId.URL


  Build-depends:       base                         > 4     && < 5,
                       bytestring                   >= 0.9  && < 0.13,
                       base64-bytestring            >= 1.0  && < 1.3,
                       aeson                        (>= 0.4  && < 0.10) || (>= 0.11 && < 1.6) || (>= 2.0 && < 2.4),
                       boomerang                    >= 1.4  && < 1.5,
                       containers                   >= 0.4  && < 0.9,
                       ixset-typed                  >= 0.3  && < 0.7,
                       lens                         >= 4.2  && < 5.4,
                       mtl                          >= 2.0  && < 2.4,
                       safecopy                     >= 0.8  && < 0.11,
                       shakespeare                  >= 2.0  && < 2.3,
                       text                         >= 0.11 && < 2.2,
                       userid                       >= 0.1  && < 0.2,
                       web-routes                   >= 0.26 && < 0.28,
                       web-routes-boomerang         >= 0.28 && < 0.29,
                       web-routes-th                >= 0.22 && < 0.23,

  -- flag(arch_javascript): stand-in for arch(javascript); remove if not using haskell.nix.
  if !(impl(ghcjs) || flag(arch_javascript))
    Build-depends:
                       acid-state                   >= 0.6  && < 0.17,
                       authenticate                 == 1.3.*,
                       data-default                 >= 0.5  && < 0.9,
                       email-validate               >= 2.1  && < 2.4,
                       filepath                     >= 1.3  && < 1.6,
                       hsx2hs                       >= 0.13 && < 0.15,
                       jmacro                       >= 0.6.11  && < 0.7,
                       jwt                          >= 0.3  && < 0.12,
                       happstack-jmacro             >= 7.0  && < 7.1,
                       happstack-server             >= 6.0  && < 7.10,
                       happstack-hsp                >= 7.3  && < 7.4,
                       http-conduit                 >= 2.1.0 && < 2.4,
                       http-types                   >= 0.6  && < 0.13,
                       hsp                          >= 0.10 && < 0.11,
                       hsx-jmacro                   >= 7.3  && < 7.4,
                       mime-mail                    >= 0.4  && < 0.6,
                       pwstore-purehaskell          == 2.1.*,
                       SHA                          >= 1.6  && < 1.7,
                       stm                          >= 2.4  && < 2.6,
                       time                         >= 1.2  && < 1.17,
                       random                       >= 1.0  && < 1.4,
                       unordered-containers         == 0.2.*,
                       web-routes-happstack         == 0.23.*,

test-suite happstack-authenticate-test
  import:              shared-properties
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             Spec.hs
  if impl(ghcjs) || flag(arch_javascript)
    buildable: False
  else
    build-depends:       base
                       , happstack-authenticate
                       , acid-state                   >= 0.6  && < 0.17
                       , containers                   >= 0.4  && < 0.9
                       , directory                    >= 1.2  && < 1.4
                       , filepath                     >= 1.3  && < 1.6
                       , lens                         >= 4.2  && < 5.4
                       , userid                       >= 0.1  && < 0.2

executable happstack-authenticate-client
  import: shared-ghcjs-properties
  if flag(Debug)
    cpp-options: "-DDEBUG"
  if impl(ghcjs) || (arch(javascript) || arch(wasm32))
    buildable: True
  else
    buildable: False
  hs-source-dirs:      happstack-authenticate-client
  main-is:             HappstackAuthenticateClient.hs
  build-depends:       happstack-authenticate
