HandlerNotFound: Handler Not Found.
URLDecodeFailed: Failed to decode URL.
UsernameAlreadyExists: Username already exists.
AuthorizationRequired: Authorization required.
Forbidden: Forbidden.
JSONDecodeFailed: Failed to decode JSON data.
InvalidUserId: Invalid UserId
UsernameNotAcceptable reason@UsernameProblem: Username not acceptable. #{renderMessage HappstackAuthenticateI18N ["en"] reason}
InvalidEmail: Invalid email address.



